swagger: '2.0'
info:
  title: Dottie AI Assistant API
  description: API Gateway for Dottie AI Assistant
  version: 1.0.0
host: api-gateway.dottie.example.com
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/YOUR_FIREBASE_PROJECT_ID"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "YOUR_FIREBASE_PROJECT_ID"
paths:
  /auth/status:
    get:
      summary: Get authentication status
      operationId: getAuthStatus
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/auth/status
      responses:
        '200':
          description: Authentication status
        '401':
          description: Unauthorized
  
  /auth/google:
    get:
      summary: Get Google OAuth URL
      operationId: getGoogleAuthUrl
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/auth/google
      responses:
        '200':
          description: Google OAuth URL
        '401':
          description: Unauthorized
  
  /auth/google/callback:
    get:
      summary: Google OAuth callback
      operationId: googleCallback
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/auth/google/callback
      responses:
        '200':
          description: OAuth callback successful
        '400':
          description: Bad request
  
  /chat:
    post:
      summary: Send message to chat
      operationId: sendChatMessage
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/chat
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - query
            properties:
              query:
                type: string
              conversationId:
                type: string
      responses:
        '200':
          description: Chat response
        '401':
          description: Unauthorized
  
  /gmail/messages:
    get:
      summary: Get Gmail messages
      operationId: getGmailMessages
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/gmail/messages
      parameters:
        - name: maxResults
          in: query
          type: integer
          default: 20
        - name: pageToken
          in: query
          type: string
      responses:
        '200':
          description: Gmail messages
        '401':
          description: Unauthorized
    post:
      summary: Send email
      operationId: sendEmail
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/gmail/messages
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - to
              - subject
              - body
            properties:
              to:
                type: string
              subject:
                type: string
              body:
                type: string
              cc:
                type: string
              bcc:
                type: string
              isHtml:
                type: boolean
      responses:
        '200':
          description: Email sent
        '401':
          description: Unauthorized
  
  /gmail/messages/{messageId}:
    get:
      summary: Get Gmail message by ID
      operationId: getGmailMessage
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/gmail/messages/{messageId}
      parameters:
        - name: messageId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Gmail message
        '401':
          description: Unauthorized
        '404':
          description: Message not found
  
  /calendar/events:
    get:
      summary: Get calendar events
      operationId: getCalendarEvents
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/calendar/events
      parameters:
        - name: timeMin
          in: query
          type: string
        - name: timeMax
          in: query
          type: string
        - name: maxResults
          in: query
          type: integer
          default: 10
        - name: pageToken
          in: query
          type: string
      responses:
        '200':
          description: Calendar events
        '401':
          description: Unauthorized
    post:
      summary: Create calendar event
      operationId: createCalendarEvent
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/calendar/events
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - summary
              - start
              - end
            properties:
              summary:
                type: string
              description:
                type: string
              location:
                type: string
              start:
                type: object
              end:
                type: object
              attendees:
                type: array
      responses:
        '200':
          description: Event created
        '401':
          description: Unauthorized
  
  /calendar/events/{eventId}:
    get:
      summary: Get calendar event by ID
      operationId: getCalendarEvent
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/calendar/events/{eventId}
      parameters:
        - name: eventId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Calendar event
        '401':
          description: Unauthorized
        '404':
          description: Event not found
    put:
      summary: Update calendar event
      operationId: updateCalendarEvent
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/calendar/events/{eventId}
      parameters:
        - name: eventId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Event updated
        '401':
          description: Unauthorized
        '404':
          description: Event not found
    delete:
      summary: Delete calendar event
      operationId: deleteCalendarEvent
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/calendar/events/{eventId}
      parameters:
        - name: eventId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Event deleted
        '401':
          description: Unauthorized
        '404':
          description: Event not found
  
  /sheets/data:
    get:
      summary: Get spreadsheet data
      operationId: getSpreadsheetData
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/sheets/data
      parameters:
        - name: spreadsheetId
          in: query
          required: true
          type: string
        - name: ranges
          in: query
          type: array
          items:
            type: string
      responses:
        '200':
          description: Spreadsheet data
        '401':
          description: Unauthorized
        '404':
          description: Spreadsheet not found
    post:
      summary: Update spreadsheet data
      operationId: updateSpreadsheetData
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/sheets/data
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - spreadsheetId
              - range
              - values
            properties:
              spreadsheetId:
                type: string
              range:
                type: string
              values:
                type: array
      responses:
        '200':
          description: Spreadsheet updated
        '401':
          description: Unauthorized
        '404':
          description: Spreadsheet not found
  
  /sheets/create:
    post:
      summary: Create spreadsheet
      operationId: createSpreadsheet
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/sheets/create
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
              sheets:
                type: array
      responses:
        '200':
          description: Spreadsheet created
        '401':
          description: Unauthorized
  
  /sheets/list:
    get:
      summary: Get spreadsheets list
      operationId: getSpreadsheets
      security:
        - firebase: []
      x-google-backend:
        address: https://dottie-backend-UNIQUE_ID.a.run.app/sheets/list
      parameters:
        - name: maxResults
          in: query
          type: integer
          default: 10
      responses:
        '200':
          description: Spreadsheets list
        '401':
          description: Unauthorized
