steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']
    id: 'build-image'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
    id: 'push-image'
    waitFor: ['build-image']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: 'deploy-backend'
    waitFor: ['push-image']
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--service-account'
      - '${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'FIREBASE_CONFIG=firebase-config:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,SESSION_SECRET=session-secret:latest'
      - '--update-env-vars'
      - 'NODE_ENV=${_ENVIRONMENT}'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
    
  # Get the URL of the deployed Cloud Run service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    id: 'get-backend-url'
    waitFor: ['deploy-backend']
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe dottie-backend --region=us-central1 --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        echo "$BACKEND_URL" > /workspace/backend_url.txt
    
  # Process API Gateway configuration with the backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/bash
    id: 'process-api-config'
    waitFor: ['get-backend-url']
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        PROJECT_ID=$PROJECT_ID
        
        # Process the API Gateway configuration file
        sed -i "s|\${BACKEND_URL}|$BACKEND_URL|g" /workspace/terraform/api.yaml
        sed -i "s|\${PROJECT_ID}|$PROJECT_ID|g" /workspace/terraform/api.yaml
        
        echo "API Gateway configuration processed with Backend URL: $BACKEND_URL and Project ID: $PROJECT_ID"

images:
  - 'gcr.io/$PROJECT_ID/dottie-backend:$COMMIT_SHA'

timeout: 1800s
